CREATE TABLE community {
    id PRIMARY KEY VARCHAR(40) DEFAULT (uuid())
    name VARCHAR(64) NOT NULL UNIQUE
    lat REAL NOT NULL
    lon REAL NOT NULL
    currency VARCHAR(16) NOT NULL
}

CREATE TABLE user {
    id PRIMARY KEY VARCHAR(40) DEFAULT (uuid())
    name VARCHAR(64) NOT NULL
    email VARCHAR(320) NOT NULL UNIQUE
    age INTEGER NOT NULL
    city VARCHAR(64) NOT NULL
    address VARCHAR(128) NOT NULL
    communityId VARCHAR(40) NOT NULL
    FOREIGN KEY (communityId) REFERENCES community.id ON DELETE CASCADE
}

CREATE TABLE post {
    id PRIMARY KEY VARCHAR(40) DEFAULT (uuid())
    type INTEGER NOT NULL
    creationDate DATE NOT NULL
    createdBy VARCHAR(40) NOT NULL
    FOREIGN KEY (createdBy) REFERENCES user.id ON DELETE CASCADE 
}