DELETE FROM REQUEST;
DELETE FROM MESSAGE;
DELETE FROM USER;
DELETE FROM COMMUNITY_EVENT;
DELETE FROM HOUSE;
DELETE FROM COMMUNITY;

DROP TABLE REQUEST;
DROP TABLE MESSAGE;
DROP TABLE USER;
DROP TABLE COMMUNITY_EVENT;
DROP TABLE HOUSE;
DROP TABLE COMMUNITY;
